[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/SixingWang2025"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "rss"
    name       = "RSS"
    url        = "/index.xml"

    [social.params]
        icon = "rss"

[[social]]
    identifier = "nav"
    name       = "导航"
    url        = "https://sixingwang2025.github.io/nav/"

    [social.params]
        icon = "link"

[[social]]
    identifier = "page"
    name       = "个人主页"
    url        = "https://sixingwang2025.github.io/page/"

    [social.params]
        icon = "home"
