[[social]]
    identifier = "page"
    name       = "个人主页"
    url        = "https://sixingwang2025.github.io/page/"
    weight     = 1
    params     = { icon = "home" }

[[social]]
    identifier = "nav"
    name       = "导航"
    url        = "https://sixingwang2025.github.io/nav/"
    weight     = 2
    params     = { icon = "chevron-right" }

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/SixingWang2025"
    weight     = 3
    params     = { icon = "brand-github" }

[[social]]
    identifier = "rss"
    name       = "RSS"
    url        = "/index.xml"
    weight     = 4
    params     = { icon = "rss" }
